import type { Metadata } from "next";
import "./globals.css";
import Footer from "@components/layout/Footer";
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: "Smart ArtTech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
      >
        <NextTopLoader color="#4B2CED" showSpinner={false} />
       
        <div className="pt-[30px] bg-[#AFAFAF] px-[30px] max-900:px-[20px] max-900:pt-[30px]">
          {children}

        </div>

              <Footer />

       
      </body>
    </html>
  );
}
